blueprint:
  name: Arya's Ultimate Room Climate Control (v0.1.3)
  author: AryaNakh
  homeassistant:
    min_version: 2023.1.0
  description: >
    Controls the central thermostat based on one prioritized room sensor.
    Main check: every 10 minutes
    Quick reaction: if room temperature changes by ≥ 0.8 °F
    Adjustable aggressiveness via multiplier.
    Comfort range set when room is within desired band.

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      description: The central climate entity (e.g. climate.upstairs)
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Prioritized Room Sensor
      description: Temperature sensor for the room to control
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Desired Min Temp (°F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 68

    max_temperature:
      name: Desired Max Temp (°F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 70

    control_mode:
      name: Mode for Active Adjustments
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
      default: heat_cool

    adjustment_multiplier:
      name: Adjustment Multiplier (Aggressiveness)
      description: 1.0 = mild, 1.5 = balanced, 2.0 = aggressive
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.1
          mode: slider
      default: 1.5

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | round(1) }}"
  control_mode: !input control_mode
  use_range_mode: "{{ control_mode in ['heat_cool', 'auto'] }}"
  multiplier: !input adjustment_multiplier

trigger:
  # Main periodic check — every 10 minutes
  - platform: time_pattern
    minutes: "/10"

  # Quick reaction when room temperature actually moves meaningfully
  - platform: numeric_state
    entity_id: !input room_sensor
    above: "{{ (states(room_sensor) | float(0) + 0.8) | round(1) }}"
    below: "{{ (states(room_sensor) | float(0) - 0.8) | round(1) }}"

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor))
         and states(thermostat) not in ['off', 'unavailable'] }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(65) }}"
      deviation: "{{ (room_temp - target_temp) | abs | round(2) }}"
      desired_setpoint: "{{ (target_temp - (multiplier * (room_temp - target_temp))) | round(1) }}"
      current_setpoint: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      current_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      current_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"

  # Debug log every time it runs
  - service: system_log.write
    data:
      message: >
        Climate check @ {{ now().strftime('%H:%M') }} — Room: {{ room_temp }}°F
        Deviation: {{ deviation }}°F | Desired: {{ desired_setpoint }}°F
        Current setpoint: {{ current_setpoint }} | Multiplier: {{ multiplier }}
      level: info

  # Only adjust if meaningfully off or wrong current setting
  - condition: or
    conditions:
      - "{{ deviation > 0.9 }}"   # roughly 1°F or more off target
      - condition: template
        value_template: >
          {% if use_range_mode %}
            {{ current_low is none or current_high is none
               or current_low != min_temp or current_high != max_temp }}
          {% else %}
            {{ current_setpoint is none
               or (desired_setpoint - current_setpoint) | abs > 0.7 }}
          {% endif %}

  - choose:
      # Too cold
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - delay: "00:00:03"   # small delay — helps some thermostats
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      # Too hot
      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: cool
          - delay: "00:00:03"
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      # Comfort zone
      - conditions: []
        sequence:
          - choose:
              - conditions:
                  - "{{ use_range_mode }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      target_temp_low: "{{ min_temp | round(1) }}"
                      target_temp_high: "{{ max_temp | round(1) }}"

              - conditions: []
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      temperature: "{{ target_temp }}"

  # Log actual adjustment
  - service: system_log.write
    data:
      message: "Adjustment applied → setpoint → {{ desired_setpoint }}°F"
      level: info

mode: single
