blueprint:
  name: Arya's Ultimate Room Climate Control
  author: AryaNakh
  homeassistant:
    min_version: 2023.1.0
  description: >
    This blueprint turns your central thermostat into a "room-first" climate controller.
    It ignores the thermostat's built-in sensor (usually in a hallway) and uses a real room sensor to keep that specific room in your desired temperature range.
    
    How it works:
    • If the room is too hot → lowers the thermostat setpoint to force more cooling
    • If the room is too cold → raises the thermostat setpoint to force more heating
    • If the room is perfect → sets a comfortable range (target_temp_low / high) in heat_cool or auto mode — or a neutral single setpoint otherwise
    
    The aggressive compensation formula (2 × desired - actual room temp) is only used when the room is actually out of range.

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      description: Your main climate entity which controls the HVAC unit (e.g. climate.upstairs_thermostat)
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Room Temperature Sensor
      description: The sensor in the room you actually care about (e.g. sensor.nursery_temperature)
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Minimum Desired Temperature
      description: Lowest temperature the room should ever be (e.g. 68 °F for the nursery)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
          unit_of_measurement: "°F"
      default: 68

    max_temperature:
      name: Maximum Desired Temperature
      description: Highest temperature the room should ever be (e.g. 70 °F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
          unit_of_measurement: "°F"
      default: 70

    control_mode:
      name: Control HVAC Mode
      description: The mode used when actively controlling (forcing heat/cool). For neutral/"happy" state, heat_cool or auto will use a range; heat or cool will use single setpoint.
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
          sort: false
      default: heat_cool

    check_every_minutes:
      name: Check Frequency
      description: How often to check and adjust (in minutes). 5–10 minutes is usually ideal.
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: minutes
      default: 10

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | float }}"
  control_mode: !input control_mode
  use_range_mode: "{{ control_mode in ['heat_cool', 'auto'] }}"

trigger:
  - platform: time_pattern
    minutes: "/{{ check_every_minutes | int }}"
  - platform: numeric_state
    entity_id: !input room_sensor
    above: "{{ (states(room_sensor) | float(0) - 1) | round(1) }}"
    below: "{{ (states(room_sensor) | float(0) + 1) | round(1) }}"

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor)) and 
         states(thermostat) in ['heat', 'cool', 'heat_cool', 'auto'] }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(0) }}"
      current_temp: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      current_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      current_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"
      desired_setpoint: "{{ (2 * target_temp - room_temp) | round(1) }}"

  - condition: or
    conditions:
      - "{{ room_temp < min_temp or room_temp > max_temp }}"
      - condition: template
        value_template: >
          {% if use_range_mode %}
            {{ current_low is none or current_high is none 
               or current_low | round(1) != min_temp | round(1)
               or current_high | round(1) != max_temp | round(1) }}
          {% else %}
            {{ current_temp is none or (desired_setpoint - current_temp) | abs > 0.8 }}
          {% endif %}

  - choose:
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      - conditions: []
        sequence:
          - choose:
              - conditions:
                  - "{{ use_range_mode }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      target_temp_low: "{{ min_temp | round(1) }}"
                      target_temp_high: "{{ max_temp | round(1) }}"

              - conditions: []
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      temperature: "{{ target_temp | round(1) }}"

mode: single
