blueprint:
  name: AryaNakh's Ultimate Room Climate Control - (v0.1.5b)
  author: AryaNakh
  homeassistant:
    min_version: 2023.1.0
  version: 0.1.5b
  description: |
    # AryaNakh's Ultimate Room Climate Control (v0.1.5b)

    Take control of your HVAC system at home. Control system based on room sensors and more!
    I plan on rolling out features and capabilities as I need them for my own step up. 

    # Current Features
      - Control a Thermostat with a room sensor 
      - Custom re-polling durations
      - Set temperature ranging for primary room
      - Aggressive correction when room out of range
      - Wide comfort band when room is happy (user min/max + buffer)
      - Adjustable aggressiveness and buffer

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      description: e.g. climate.upstairs_thermostat
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Room Temperature Sensor
      description: e.g. sensor.nursery_environment_sensor_temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Desired Min Temp (°F) – comfort floor
      default: 68
      selector:
        number:
          min: 55
          max: 80
          step: 0.5

    max_temperature:
      name: Desired Max Temp (°F) – comfort ceiling
      default: 70
      selector:
        number:
          min: 55
          max: 80
          step: 0.5

    control_mode:
      name: Active Mode (for forcing adjustments)
      description: heat_cool or auto recommended
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
      default: heat_cool

    adjustment_multiplier:
      name: Aggressiveness Multiplier
      description: 1.0 = gentle, 1.5 = balanced, 2.0 = strong
      default: 1.5
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.1
          mode: slider

    neutral_buffer:
      name: Neutral Range Buffer (°F)
      description: Extra margin added/removed when room is happy → wider deadband
      default: 2.0
      selector:
        number:
          min: 0.5
          max: 4.0
          step: 0.5

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | round(1) }}"
  control_mode: !input control_mode
  use_range_mode: "{{ control_mode in ['heat_cool', 'auto'] }}"
  multiplier: !input adjustment_multiplier
  buffer: !input neutral_buffer

trigger:
  - platform: time_pattern
    minutes: "/10"

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor)) and states(thermostat) not in ['off', 'unavailable'] }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(65) }}"
      deviation: "{{ (room_temp - target_temp) | abs | round(2) }}"
      desired_setpoint: "{{ (target_temp - (multiplier * (room_temp - target_temp))) | round(1) }}"
      neutral_low: "{{ (min_temp - buffer) | round(1) }}"
      neutral_high: "{{ (max_temp + buffer) | round(1) }}"
      current_setpoint: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      current_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      current_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"

  - service: system_log.write
    data:
      message: >
        Check {{ now().strftime('%H:%M') }} | Room {{ room_temp }}°F (dev {{ deviation }}°F)
        Desired {{ desired_setpoint }}°F | Current {{ current_setpoint }}
        Neutral range would be {{ neutral_low }}–{{ neutral_high }}°F
      level: info

  - condition: or
    conditions:
      - "{{ deviation > 0.9 }}"
      - condition: template
        value_template: >
          {% if use_range_mode %}
            {{ current_low is none or current_high is none or current_low != neutral_low or current_high != neutral_high }}
          {% else %}
            {{ current_setpoint is none or (desired_setpoint - current_setpoint) | abs > 0.7 }}
          {% endif %}

  - choose:
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - delay:
              seconds: 3
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: cool
          - delay:
              seconds: 3
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      - conditions: []
        sequence:
          - choose:
              - conditions:
                  - "{{ use_range_mode }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      target_temp_low: "{{ neutral_low }}"
                      target_temp_high: "{{ neutral_high }}"
                  - service: system_log.write
                    data:
                      message: "Room happy → set wide comfort band {{ neutral_low }}–{{ neutral_high }}°F"
                      level: info

              - conditions: []
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      temperature: "{{ target_temp }}"

  - service: system_log.write
    data:
      message: "Adjustment completed"
      level: info

mode: single
