blueprint:
  name: Arya's Ultimate Room Climate Control - 10 Min Only Clean
  author: AryaNakh
  homeassistant:
    min_version: 2023.1.0
  description: >
    Reliable central thermostat control using one prioritized room sensor.
    - Runs every 10 minutes (at :00, :10, :20, etc.)
    - Uses compensation formula with adjustable multiplier when room is out of range
    - Sets broad comfort range (target_temp_low / high) when room is within desired temperatures
    - Debug logging in system logs

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      description: e.g. climate.upstairs_thermostat
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Room Temperature Sensor
      description: e.g. sensor.nursery_environment_sensor_temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Min Desired Temp (°F)
      default: 68
      selector:
        number:
          min: 55
          max: 80
          step: 0.5

    max_temperature:
      name: Max Desired Temp (°F)
      default: 70
      selector:
        number:
          min: 55
          max: 80
          step: 0.5

    control_mode:
      name: Active Mode (for forcing adjustments)
      description: heat_cool or auto recommended for proper range support when room is happy
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
      default: heat_cool

    adjustment_multiplier:
      name: Aggressiveness Multiplier
      description: 1.0 = gentle correction, 1.5 = balanced, 2.0 = strong push
      default: 1.5
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.1
          mode: slider

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | round(1) }}"
  control_mode: !input control_mode
  use_range_mode: "{{ control_mode in ['heat_cool', 'auto'] }}"
  multiplier: !input adjustment_multiplier

trigger:
  - platform: time_pattern
    minutes: "/10"

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor)) and states(thermostat) not in ['off', 'unavailable'] }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(65) }}"
      deviation: "{{ (room_temp - target_temp) | abs | round(2) }}"
      desired_setpoint: "{{ (target_temp - (multiplier * (room_temp - target_temp))) | round(1) }}"
      current_setpoint: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      current_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      current_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"

  - service: system_log.write
    data:
      message: >
        Climate check {{ now().strftime('%H:%M') }} | Room: {{ room_temp }}°F (dev {{ deviation }}°F)
        Desired: {{ desired_setpoint }}°F | Current setpoint: {{ current_setpoint }}
      level: info

  - condition: or
    conditions:
      - "{{ deviation > 0.9 }}"
      - condition: template
        value_template: >
          {% if use_range_mode %}
            {{ current_low is none or current_high is none or current_low != min_temp or current_high != max_temp }}
          {% else %}
            {{ current_setpoint is none or (desired_setpoint - current_setpoint) | abs > 0.7 }}
          {% endif %}

  - choose:
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - delay:
              seconds: 3
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: cool
          - delay:
              seconds: 3
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      - conditions: []
        sequence:
          - choose:
              - conditions:
                  - "{{ use_range_mode }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      target_temp_low: "{{ min_temp | round(1) }}"
                      target_temp_high: "{{ max_temp | round(1) }}"
                  - service: system_log.write
                    data:
                      message: "Room in range → set comfort band {{ min_temp }}–{{ max_temp }}°F"
                      level: info

              - conditions: []
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      temperature: "{{ target_temp }}"

  - service: system_log.write
    data:
      message: "Adjustment applied → setpoint: {{ desired_setpoint }}°F"
      level: info

mode: single
