blueprint:
  name: Arya's Ultimate Room Climate Control - (v0.1.2)
  author: AryaNakh
  homeassistant:
    min_version: 2025.1.0
  description: >
    Prioritizes one room's temperature sensor over the hallway thermostat.
    Forces heat/cool when out of range using adjustable aggressiveness.
    Sets comfort range or midpoint when the room is within desired temperatures.
    
    The adjustment formula is:
    desired_setpoint = target_temp - multiplier × (room_temp - target_temp)
    • multiplier 1.0 = mild compensation
    • 1.5 = balanced (recommended starting point)
    • 2.0 = aggressive (original behavior)

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      description: The central climate entity (e.g. climate.upstairs)
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Prioritized Room Sensor
      description: Temperature sensor for the room to control (e.g. sensor.nursery_temp)
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Desired Min Temp (°F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 68

    max_temperature:
      name: Desired Max Temp (°F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 70

    control_mode:
      name: Mode for Active Adjustments
      description: Used when forcing heat/cool. Neutral uses range if possible.
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
      default: heat_cool

    adjustment_multiplier:
      name: Adjustment Multiplier (Aggressiveness)
      description: How strongly to push when out of range. 1.0 = mild, 1.5 = balanced, 2.0 = aggressive
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.1
          mode: slider
      default: 1.5

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | round(1) }}"
  control_mode: !input control_mode
  use_range_mode: "{{ control_mode in ['heat_cool', 'auto'] }}"
  multiplier: !input adjustment_multiplier

trigger:
  # Periodic check every 10 minutes (edit YAML after import for different interval)
  - platform: time_pattern
    minutes: "/10"

  # React to room temperature changes (with 1-minute debounce)
  - platform: state
    entity_id: !input room_sensor
    for:
      minutes: 1

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor))
         and states(thermostat) not in ['off', 'unavailable'] }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(65) }}"  # safe fallback
      deviation: "{{ room_temp - target_temp }}"
      desired_setpoint: "{{ (target_temp - (multiplier * deviation)) | round(1) }}"
      current_setpoint: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      current_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      current_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"

  # Debug log: always record when triggered
  - service: system_log.write
    data:
      message: >
        Climate check - Room: {{ room_temp }}°F | Target: {{ target_temp }}°F | Deviation: {{ deviation | round(1) }}°F | Desired setpoint: {{ desired_setpoint }}°F | Current: {{ current_setpoint }} | Multiplier: {{ multiplier }}
      level: info

  # Only adjust if meaningfully off or wrong setpoint/range currently set
  - condition: or
    conditions:
      - "{{ room_temp < min_temp - 0.5 or room_temp > max_temp + 0.5 }}"
      - condition: template
        value_template: >
          {% if use_range_mode %}
            {{ current_low is none or current_high is none or current_low != min_temp or current_high != max_temp }}
          {% else %}
            {{ current_setpoint is none or (desired_setpoint - current_setpoint) | abs > 0.8 }}
          {% endif %}

  - choose:
      # Too cold: force heat + adjusted setpoint
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      # Too hot: force cool + adjusted setpoint
      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      # In range: set comfort band or midpoint
      - conditions: []
        sequence:
          - choose:
              - conditions:
                  - "{{ use_range_mode }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      target_temp_low: "{{ min_temp | round(1) }}"
                      target_temp_high: "{{ max_temp | round(1) }}"

              - conditions: []
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      temperature: "{{ target_temp }}"

mode: restart
