blueprint:
  name: Arya's Ultimate Room Climate Control (v0.1)
  author: AryaNakh
  homeassistant:
    min_version: 2023.1.0
  description: >
    Prioritizes one room's temperature sensor over the hallway thermostat.
    Forces heat/cool aggressively when out of range; sets comfort range or midpoint when ok.
    Logs actions to system log for debugging.
    Version (v0.1.1)

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      description: The central climate entity (e.g. climate.upstairs)
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Prioritized Room Sensor
      description: Temperature sensor for the room to control (e.g. sensor.nursery_temp)
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Desired Min Temp (째F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 68

    max_temperature:
      name: Desired Max Temp (째F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 70

    control_mode:
      name: Mode for Active Adjustments
      description: Used when forcing heat/cool. Neutral uses range if possible.
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
      default: heat_cool

    check_interval_minutes:
      name: Periodic Check Interval (minutes)
      description: How often to force-check (static; edit YAML for odd values)
      selector:
        number:
          min: 5
          max: 30
          step: 5
      default: 10

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | round(1) }}"
  control_mode: !input control_mode
  use_range_mode: "{{ control_mode in ['heat_cool', 'auto'] }}"

trigger:
  # Periodic check (every 10 min at aligned times; change /10 in YAML if needed after import)
  - platform: time_pattern
    minutes: "/10"

  # React to room temp changes (debounce to avoid noise)
  - platform: state
    entity_id: !input room_sensor
    for:
      minutes: 1

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor))
         and states(thermostat) not in ['off', 'unavailable'] }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(65) }}"  # safe fallback
      desired_setpoint: "{{ (2 * target_temp - room_temp) | round(1) }}"
      current_setpoint: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      current_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      current_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"

  # Debug log: always write on trigger
  - service: system_log.write
    data:
      message: >
        Climate check triggered. Room: {{ room_temp }}째F | Target: {{ target_temp }}째F | Setpoint: {{ current_setpoint }} | Low/High: {{ current_low }}/{{ current_high }}
      level: info

  # Only adjust if meaningfully off or wrong mode/range set
  - condition: or
    conditions:
      - "{{ room_temp < min_temp - 0.5 or room_temp > max_temp + 0.5 }}"
      - condition: template
        value_template: >
          {% if use_range_mode %}
            {{ current_low is none or current_high is none or current_low != min_temp or current_high != max_temp }}
          {% else %}
            {{ current_setpoint is none or (desired_setpoint - current_setpoint) | abs > 0.8 }}
          {% endif %}

  - choose:
      # Too cold: force heat + aggressive low setpoint
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: heat
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      # Too hot: force cool + aggressive high setpoint
      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ desired_setpoint }}"

      # In range: set comfort band or midpoint
      - conditions: []
        sequence:
          - choose:
              - conditions:
                  - "{{ use_range_mode }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      target_temp_low: "{{ min_temp | round(1) }}"
                      target_temp_high: "{{ max_temp | round(1) }}"

              - conditions: []
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: !input thermostat
                    data:
                      hvac_mode: !input control_mode
                  - service: climate.set_temperature
                    target:
                      entity_id: !input thermostat
                    data:
                      temperature: "{{ target_temp }}"

mode: restart
