blueprint:
  name: Arya's Ultimate Room Climate Control - Fixed
  author: AryaNakh (improved with community patterns)
  homeassistant:
    min_version: 2023.1.0
  description: >
    Prioritizes a room sensor over the thermostat's built-in one. Forces aggressive correction when out of range, sets comfort band when ok.
    Debug logs added. Use with heat_cool/auto thermostats for best range support.

  domain: automation
  input:
    thermostat:
      name: Main Thermostat
      selector:
        entity:
          domain: climate

    room_sensor:
      name: Room Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    min_temperature:
      name: Min Desired Temp (°F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 68

    max_temperature:
      name: Max Desired Temp (°F)
      selector:
        number:
          min: 55
          max: 80
          step: 0.5
      default: 70

    control_mode:
      name: Active Control Mode
      selector:
        select:
          options:
            - heat_cool
            - auto
            - heat
            - cool
      default: heat_cool

    check_interval_minutes:
      name: Check Every (minutes)
      selector:
        number:
          min: 5
          max: 30
          step: 5
      default: 10

    hysteresis:
      name: Adjustment Hysteresis (°F)
      description: Only adjust if deviation exceeds this (reduces spam)
      selector:
        number:
          min: 0.3
          max: 2
          step: 0.1
      default: 0.8

variables:
  thermostat: !input thermostat
  room_sensor: !input room_sensor
  min_temp: !input min_temperature
  max_temp: !input max_temperature
  target_temp: "{{ ((min_temp + max_temp) / 2) | round(1) }}"
  control_mode: !input control_mode
  use_range: "{{ control_mode in ['heat_cool', 'auto'] }}"
  interval: !input check_interval_minutes
  hyst: !input hysteresis

trigger:
  # Periodic: use time_pattern with static modulo-like (fires at :00, :10, :20... for 10 min)
  - platform: time_pattern
    minutes: "{{ '/'+ interval | string if interval <= 30 else '/10' }}"

  # Room temp change (debounce 2 min to avoid tiny updates)
  - platform: state
    entity_id: !input room_sensor
    for:
      minutes: 2

condition:
  - condition: template
    value_template: >
      {{ is_number(states(room_sensor)) 
         and not is_state(thermostat, ['off', 'unavailable']) 
         and is_number(state_attr(thermostat, 'current_temperature') | default(0)) }}

action:
  - variables:
      room_temp: "{{ states(room_sensor) | float(65) }}"  # fallback if bad
      curr_temp: "{{ state_attr(thermostat, 'temperature') | float(none) }}"
      curr_low: "{{ state_attr(thermostat, 'target_temp_low') | float(none) }}"
      curr_high: "{{ state_attr(thermostat, 'target_temp_high') | float(none) }}"
      desired: "{{ (2 * target_temp - room_temp) | round(1) }}"
      deviation: "{{ (room_temp - target_temp) | abs }}"

  # Log start
  - service: system_log.write
    data:
      message: "Room Climate Check: room={{room_temp}}°F target={{target_temp}}°F deviation={{deviation}}"
      level: info

  # Skip if within hysteresis band
  - condition: template
    value_template: "{{ deviation > hyst or curr_temp is none or (use_range and (curr_low != min_temp or curr_high != max_temp)) }}"

  - choose:
      - conditions:
          - "{{ room_temp < min_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target: {entity_id: !input thermostat}
            data: {hvac_mode: heat}
          - service: climate.set_temperature
            target: {entity_id: !input thermostat}
            data: {temperature: "{{ desired }}"}
          - service: system_log.write
            data:
              message: "Too cold → Heat mode, setpoint={{desired}}"
              level: info

      - conditions:
          - "{{ room_temp > max_temp }}"
        sequence:
          - service: climate.set_hvac_mode
            target: {entity_id: !input thermostat}
            data: {hvac_mode: cool}
          - service: climate.set_temperature
            target: {entity_id: !input thermostat}
            data: {temperature: "{{ desired }}"}
          - service: system_log.write
            data:
              message: "Too hot → Cool mode, setpoint={{desired}}"
              level: info

      # Neutral
      - conditions: []
        sequence:
          - choose:
              - conditions: "{{ use_range }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target: {entity_id: !input thermostat}
                    data: {hvac_mode: !input control_mode}
                  - service: climate.set_temperature
                    target: {entity_id: !input thermostat}
                    data:
                      target_temp_low: "{{ min_temp | round(1) }}"
                      target_temp_high: "{{ max_temp | round(1) }}"
                  - service: system_log.write
                    data:
                      message: "Neutral range set: {{min_temp}}-{{max_temp}}"
                      level: info

              - sequence:
                  - service: climate.set_hvac_mode
                    target: {entity_id: !input thermostat}
                    data: {hvac_mode: !input control_mode}
                  - service: climate.set_temperature
                    target: {entity_id: !input thermostat}
                    data: {temperature: "{{ target_temp }}"}
                  - service: system_log.write
                    data:
                      message: "Neutral single setpoint: {{target_temp}}"
                      level: info

mode: restart  # Allows re-trigger if long-running
max_exceeded: silent
